deployment:
  tasks:
    - cd /home/ruat9133/repositories/ruangjiwadanadyaksa && git pull origin main
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/composer dump-autoload
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - rsync -av --delete public/build/ /home/ruat9133/public_html/
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan view:clear
    - php artisan route:clear
